services:
  web:
    image: bitnami/laravel
    env_file: "laravel.env"
    networks:
      - internal
    ports:
      - "8080:8080"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./lara-app:/app"
    user: "1000"
    depends_on:
      db:
        condition: service_healthy
        
  vite:
    image: node
    networks:
      - internal
    ports:
      - "8081:8081"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./lara-app:/app"
    user: "1000"
    working_dir: "/app"
    command: "yarn run dev --host 0.0.0.0 --port 8081"
  
  db:
    image: bitnami/mariadb
    env_file: "mariadb.env"
    networks:
      - internal
    ports:
      - "33060:3306"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./maria-data:/bitnami/mariadb"
    user: "1000"
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/mariadb/healthcheck.sh"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
        
networks:
  internal:
    driver: bridge
    
