services:
  web:
    image: bitnami/laravel
    environment:
      TZ: "Asia/Taipei"
    env_file: "laravel.env"
    networks:
      - internal
    ports:
      - "8000:8000"
    volumes:
      - ./lara-app:/app
    user: "1000"
    depends_on:
      database:
        condition: service_healthy
  
  database:
    image: bitnami/mariadb
    environment:
      TZ: "Asia/Taipei"
    env_file: "mariadb.env"
    networks:
      - internal
    volumes:
      - ./maria-data:/bitnami/mariadb
    user: "1000"
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/mariadb/healthcheck.sh"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
        
networks:
  internal:
    driver: bridge
    
